Revert "Reported VSO-1663233 "/clr C++20 rejects <coroutine> with error C3861 "'__builtin_coro_done': identifier not found" instead of falling back to native codegen"."
This reverts commit 8c4074103e82525f8c5b39937e0df699d4602ed5.