flat.map.cons/deduct.pass.cpp now fails for Clang too, unknown cause (possible compiler bug?).
It's emitting:

error: no type named 'value_type' in 'std::greater<int>'

despite the fact that we've constrained with `_Allocator_for_container _Allocator`.