CUDA: Perma-workaround for designated aggregate initialization.
This was introduced by GH 5662 on 2025-08-08.
Just initialize the return value with `{}` to avoid garbage.
Use the name `_Tm` (instead of the previous `_Time`) for consistency with other returns.

Avoids host compiler error C2760: syntax error: '}' was unexpected here; expected 'expression'