src/status_chart.ts: Add HiddenInfoMaps.lookup().
This avoids injecting properties into the chart datasets, fixing:
error TS2339: Property 'stl_default_hidden' does not exist on type 'ChartDataset<...>'.
error TS2339: Property 'stl_key' does not exist on type 'ChartDataset<...>'.