Product fix: Allow `locale{nullptr}` to compile.
Verified that there are no differences in release or debug exports.

Found by std/localization/locales/locale/locale.cons/char_pointer.pass.cpp with:

D:\GitHub\STL\llvm-project\libcxx\test\std\localization\locales\locale\locale.cons\char_pointer.pass.cpp(92): error C2440: '<function-style-cast>': cannot convert from 'nullptr' to 'std::locale'
D:\GitHub\STL\llvm-project\libcxx\test\std\localization\locales\locale\locale.cons\char_pointer.pass.cpp(92): note: 'std::locale::locale': ambiguous call to overloaded function
D:\GitHub\STL\out\x64\out\inc\xlocale(304): note: could be 'std::locale::locale(const char *,std::locale::category)'
D:\GitHub\STL\out\x64\out\inc\xlocale(394): note: or       'std::locale::locale(std::locale::_Locimp *)'
D:\GitHub\STL\llvm-project\libcxx\test\std\localization\locales\locale\locale.cons\char_pointer.pass.cpp(92): note: while trying to match the argument list '(nullptr)'