tests: We don't need /Zc:strictStrings anymore.
This is implied by /permissive- (and therefore /std:c++20), so we have extensive coverage.

    C:\Temp>type meow.cpp
    #include <iostream>

    int main() {
        char* ptr = "Goodbye, deprecated world!\n";
        std::cout << ptr;
    }

    C:\Temp>cl /EHsc /nologo /W4 meow.cpp && meow
    meow.cpp
    Goodbye, deprecated world!

    C:\Temp>cl /EHsc /nologo /W4 /Zc:strictStrings meow.cpp && meow
    meow.cpp
    meow.cpp(4): error C2440: 'initializing': cannot convert from 'const char [28]' to 'char *'
    meow.cpp(4): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)

    C:\Temp>cl /EHsc /nologo /W4 /permissive- meow.cpp && meow
    meow.cpp
    meow.cpp(4): error C2440: 'initializing': cannot convert from 'const char [28]' to 'char *'
    meow.cpp(4): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)

    C:\Temp>cl /EHsc /nologo /W4 /std:c++20 meow.cpp && meow
    meow.cpp
    meow.cpp(4): error C2440: 'initializing': cannot convert from 'const char [28]' to 'char *'
    meow.cpp(4): note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)