Reported VSO-1659383 '/clr atomic and thread emit error C2711 "this function cannot be compiled as managed" instead of falling back to native codegen'.